TOP = ../..
include $(TOP)/configure/CONFIG
# Set ARCH to the target architecture for this IOC instance.
# Add cdCommands to TARGETS for vxWorks.
ARCH = linux-x86_64
TARGETS = envPaths
#TARGETS = cdCommands envPaths
include $(TOP)/configure/RULES.ioc
